### ISSUE TITLE
Failing travis build for multiple branches

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsalpha/connecting-to-services-hack-day#28]
Two of the GP Server Tests are failing on Travis but not locally.

 1) Server should get details for a known GP:
 2) Server should return 404 for an unknown GP:

The errors, from branch fix/gmt-offset-issue, are:

```
{ AssertionError: Invalid URL: 'http://not.real.combbccdd 12345'
    at getDetails (/home/travis/build/nhsalpha/connecting-to-services-hack-day/app/middleware/gp.js:95:3)
    at Layer.handle [as handle_request] (/home/travis/build/nhsalpha/connecting-to-services-hack-day/node_modules/express/lib/router/layer.js:95:5)

```
Note: Other branches have other failing tests but they can be replicated locally.

**Comment by neilbmclaughlin** [comment]
Fixed.
